MACHINES = {
  :"gitlab-server" => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
        :mem => "4096",
        :core => "2",
        :vm_port_http => "80",
        :host_port_http => "8080"
  },
  :"gitlab-worker" => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.155',
    :mem => "1024",
    :core => "1"
  },
  :"app-server" => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.160',
        :mem => "512",
        :core => "1",
        :vm_port_mon1 => "9100",
        :host_port_mon1 => "9110",
        :vm_port_mon2 => "9101",
        :host_port_mon2 => "9111"
   },
  :"app-client" => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.165',
    :mem => "512",
    :core => "1",
    :vm_port_mon1 => "9100",
    :host_port_mon1 => "9120",
    :vm_port_mon2 => "9101",
    :host_port_mon2 => "9121"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          if !boxconfig[:vm_port_http].nil?
          box.vm.network "forwarded_port", guest: boxconfig[:vm_port_http], host: boxconfig[:host_port_http]
          end
          if !boxconfig[:vm_port_mon1].nil?
          box.vm.network "forwarded_port", guest: boxconfig[:vm_port_mon1], host: boxconfig[:host_port_mon1]
          end
          if !boxconfig[:vm_port_mon2].nil?
            box.vm.network "forwarded_port", guest: boxconfig[:vm_port_mon2], host: boxconfig[:host_port_mon2]
          end
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", boxconfig[:mem]]
            vb.customize ["modifyvm", :id, "--cpus", boxconfig[:core]]
          end
      end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/all.yaml"
    ansible.inventory_path = "inventory"
  end
end
