---
- hosts:
   - all
  become: true
  tasks:
  - name: selinux disable 
    selinux:
      state: disabled
  
  - name: selinux polycy disable
    selinux:
      policy: targeted
      state: permissive
  
  - name: install epel repo
    yum:
      name:
      - epel-release

  - name: install packeges
    yum:
     name:
      - yum-utils
      - python-pip
      - vim
      - htop
      - wget
      - telnet
     state: present
  
  - name: disable firewall
    systemd: 
      name: firewalld
      state: stopped
      enabled: no

  - name: create dir
    file:
      path: /app
      state: directory
      mode: '0777'

  - name: add hostname in /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
    with_items:
     - '192.168.11.150 gitlab-server'
     - '192.168.11.155 gitlab-worker'
     - '192.168.11.160 app-server'
     - '192.168.11.165 app-client'

  - name: add vagrant pub key
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', './files/id_rsa.pub') }}"

  - name: add vagrant private key
    copy:
      src: ./files/id_rsa
      dest: /home/vagrant/.ssh/id_rsa
      owner: vagrant
      group: vagrant
      mode: '0600'

  - name: add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: install package docker
    yum:
      name: docker-ce
      state: present

  - name: update pip
    pip:
      name: pip==20.3.4
      state: present

  - name: fix some errors in python modules
    pip:
      name: requests
      state: absent

  - name: install python modules for docker
    pip:
      name: docker==4.4.4
      state: present
      extra_args: --ignore-installed

  - name: start and enable docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: add user vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: yes